"use client";
import { useEffect, useRef, useState } from "react";
import { MessageCircle, Send, X } from "lucide-react";

type Msg={id:string;sender:"visitor"|"admin";text:string;at:string};
export function ChatWidget(){const [open,setOpen]=useState(false),[id,setId]=useState(""),[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState("");const end=useRef<HTMLDivElement>(null);
useEffect(()=>{const saved=localStorage.getItem("velaire_chat");if(saved)setId(saved)},[]);
useEffect(()=>{if(!open||!id)return;const poll=async()=>{const r=await fetch(`/api/chat/${id}`);if(r.ok){const d=await r.json();setMessages(d.messages||[])}};poll();const t=setInterval(poll,4000);return()=>clearInterval(t)},[open,id]);
useEffect(()=>end.current?.scrollIntoView({behavior:"smooth"}),[messages]);
async function send(e:React.FormEvent){e.preventDefault();if(!text.trim())return;const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({conversationId:id||undefined,text,name,email,website:""})});if(r.ok){const d=await r.json();setId(d.id);localStorage.setItem("velaire_chat",d.id);setMessages(d.messages);setText("")}}
return <div className="fixed bottom-5 right-5 z-50">{open&&<section className="mb-3 flex h-[min(560px,calc(100vh-110px))] w-[min(380px,calc(100vw-24px))] flex-col overflow-hidden rounded-2xl border border-black/20 bg-[#fffdf8] shadow-2xl" aria-label="Live chat"><div className="flex items-center justify-between bg-[#171713] p-4 text-white"><div><p className="font-bold">Velaire concierge</p><p className="text-xs text-white/60">We usually reply within a few minutes</p></div><button onClick={()=>setOpen(false)} aria-label="Close chat"><X size={20}/></button></div><div className="flex-1 space-y-3 overflow-auto p-4"><div className="max-w-[85%] rounded-2xl rounded-tl-sm bg-[#eee8dc] p-3 text-sm">Hello. Tell us what you’re planning and we’ll point you in the right direction. If the team is away, leave your details and we’ll follow up.</div>{messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-2xl p-3 text-sm ${m.sender==="visitor"?"ml-auto rounded-tr-sm bg-[#dfff56]":"rounded-tl-sm bg-[#eee8dc]"}`}>{m.text}</div>)}<div ref={end}/></div><form onSubmit={send} className="border-t border-black/10 p-3">{!id&&<div className="mb-2 grid grid-cols-2 gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Name" className="rounded-lg border border-black/15 p-2 text-sm"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email (optional)" type="email" className="rounded-lg border border-black/15 p-2 text-sm"/></div>}<div className="flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Type a message…" className="min-w-0 flex-1 rounded-full border border-black/20 px-4" aria-label="Chat message"/><button className="grid h-11 w-11 place-items-center rounded-full bg-[#171713] text-white" aria-label="Send"><Send size={17}/></button></div></form></section>}<button onClick={()=>setOpen(!open)} className="ml-auto grid h-14 w-14 place-items-center rounded-full border border-black bg-[#dfff56] shadow-[4px_4px_0_#171713]" aria-label="Open chat"><MessageCircle/></button></div>}
